#!/usr/bin/env bash
set -euo pipefail

# CI helper: generate `docker/.env` for `docker compose` builds.
# Business context: CI/CD - Docker image build pipeline.
#
# Purpose:
# - Keep GitHub Actions workflow minimal by moving env rendering logic into `docker/`.
# - Produce a single env file shared by:
#   - Docker Compose variable substitution (ports/build args)
#   - Frontend build-time variables (Vite `VITE_*`)
#   - Backend/worker runtime variables
#
# Change record:
# - 2026-01-14: Initial version (moved from `.github/workflows/ci.yml`).
# - 2026-01-15: Add frontend feature flag to disable account editing UI in CI builds.

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
docker_dir="$(cd "${script_dir}/.." && pwd)"
env_file="${1:-${docker_dir}/.env}"

mkdir -p "$(dirname "${env_file}")"

escape_env_value() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "${value}"
}

write_kv() {
  local key="$1"
  local value="${2-}"
  printf '%s=%s\n' "${key}" "$(escape_env_value "${value}")" >> "${env_file}"
}

# Start a fresh file each run (CI should be deterministic).
cat > "${env_file}" <<'EOF'
# Generated by `docker/ci/write-ci-env.sh`.
# Do NOT commit this file.
EOF

# ------------------------------------------------------------------------------
# Docker Compose - Host Port Mapping
# ------------------------------------------------------------------------------
write_kv HOOKCODE_FRONTEND_PORT "${HOOKCODE_FRONTEND_PORT:-5173}"
write_kv HOOKCODE_BACKEND_PORT "${HOOKCODE_BACKEND_PORT:-4000}"
write_kv HOOKCODE_BACKEND_BIND "${HOOKCODE_BACKEND_BIND:-127.0.0.1}"
write_kv HOOKCODE_DB_PORT "${HOOKCODE_DB_PORT:-5432}"

# ------------------------------------------------------------------------------
# Frontend (Vite build-time)
# ------------------------------------------------------------------------------
# Cloudflare compatibility:
# - Force API base to `/api` so the browser never calls a blocked non-allowlisted port (e.g. `:8000`).
# - The frontend Nginx container proxies `/api/*` to the backend container internally (`backend:4000`).
write_kv VITE_API_BASE_URL "/api"
# Feature toggle (2026-01-15): disable account display-name/password editing in CI builds by default.
write_kv VITE_DISABLE_ACCOUNT_EDIT "${VITE_DISABLE_ACCOUNT_EDIT:-true}"

# ------------------------------------------------------------------------------
# Build / Tooling
# ------------------------------------------------------------------------------
write_kv PRISMA_ENGINES_MIRROR "${PRISMA_ENGINES_MIRROR:-}"

# ------------------------------------------------------------------------------
# Backend - Server / CORS
# ------------------------------------------------------------------------------
write_kv NODE_ENV "${NODE_ENV:-production}"
write_kv PORT "${PORT:-4000}"
write_kv HOST "${HOST:-0.0.0.0}"
write_kv ALLOWED_ORIGIN "${ALLOWED_ORIGIN:-*}"

# ------------------------------------------------------------------------------
# Backend - Database
# ------------------------------------------------------------------------------
write_kv DB_HOST "${DB_HOST:-db}"
write_kv DB_PORT "${DB_PORT:-5432}"

# Compatibility:
# - Older CI secrets may still use `HOOKCODE_DB_*`; map them if `DB_*` is not provided.
write_kv DB_USER "${DB_USER:-${HOOKCODE_DB_USER:-hookcode}}"
write_kv DB_PASSWORD "${DB_PASSWORD:-${HOOKCODE_DB_PASSWORD:-hookcode}}"
write_kv DB_NAME "${DB_NAME:-${HOOKCODE_DB_NAME:-hookcode}}"

# ------------------------------------------------------------------------------
# Backend - Auth (CI defaults should NOT be used in production)
# ------------------------------------------------------------------------------
auth_enabled_raw="${AUTH_ENABLED:-true}"
auth_enabled_norm="$(echo "${auth_enabled_raw}" | tr '[:upper:]' '[:lower:]' | xargs)"

# Deployment security:
# - If auth is enabled, require an explicit token secret to avoid accidental public deployments.
# - This protects self-hosted runners that also act as "production servers".
if [[ "${auth_enabled_norm}" == "1" || "${auth_enabled_norm}" == "true" || "${auth_enabled_norm}" == "yes" || "${auth_enabled_norm}" == "y" || "${auth_enabled_norm}" == "on" ]]; then
  if [[ -z "${AUTH_TOKEN_SECRET:-}" ]]; then
    echo "[ci] ERROR: AUTH_ENABLED=true but AUTH_TOKEN_SECRET is empty; please configure GitHub Actions secret AUTH_TOKEN_SECRET" >&2
    exit 1
  fi
fi

write_kv AUTH_ENABLED "${auth_enabled_raw}"
write_kv AUTH_TOKEN_SECRET "${AUTH_TOKEN_SECRET:-}"

bootstrap_enabled_raw="${AUTH_BOOTSTRAP_ADMIN:-true}"
bootstrap_enabled_norm="$(echo "${bootstrap_enabled_raw}" | tr '[:upper:]' '[:lower:]' | xargs)"
if [[ "${bootstrap_enabled_norm}" == "1" || "${bootstrap_enabled_norm}" == "true" || "${bootstrap_enabled_norm}" == "yes" || "${bootstrap_enabled_norm}" == "y" || "${bootstrap_enabled_norm}" == "on" ]]; then
  if [[ -z "${AUTH_ADMIN_PASSWORD:-}" ]]; then
    echo "[ci] WARN: AUTH_BOOTSTRAP_ADMIN=true but AUTH_ADMIN_PASSWORD is empty; if the DB has no users, you may not be able to log in" >&2
  fi
fi

write_kv AUTH_BOOTSTRAP_ADMIN "${bootstrap_enabled_raw}"
write_kv AUTH_ADMIN_USERNAME "${AUTH_ADMIN_USERNAME:-admin}"
write_kv AUTH_ADMIN_PASSWORD "${AUTH_ADMIN_PASSWORD:-}"
write_kv AUTH_EXEMPT_HEALTH "${AUTH_EXEMPT_HEALTH:-true}"

# ------------------------------------------------------------------------------
# GitLab / GitHub Integration (dummy values for build-only CI)
# ------------------------------------------------------------------------------
write_kv GITLAB_WEBHOOK_SECRET "${GITLAB_WEBHOOK_SECRET:-ci-test-webhook-secret}"
write_kv GITLAB_PERSONAL_ACCESS_TOKEN "${GITLAB_PERSONAL_ACCESS_TOKEN:-dummy-token-for-ci-build}"
write_kv GITHUB_WEBHOOK_SECRET "${GITHUB_WEBHOOK_SECRET:-ci-test-webhook-secret}"
write_kv GITHUB_PERSONAL_ACCESS_TOKEN "${GITHUB_PERSONAL_ACCESS_TOKEN:-dummy-token-for-ci-build}"

# ------------------------------------------------------------------------------
# Feature toggles (keep CI fast & predictable)
# ------------------------------------------------------------------------------
# Enable task log capture in CI deployments so the Live logs SSE UI works out of the box. 0nazpc53wnvljv5yh7c6
write_kv TASK_LOGS_ENABLED "${TASK_LOGS_ENABLED:-false}"
write_kv ADMIN_TOOLS_ENABLED "${ADMIN_TOOLS_ENABLED:-false}"
write_kv INLINE_WORKER_ENABLED "${INLINE_WORKER_ENABLED:-false}"
write_kv WORKER_POLL_INTERVAL_MS "${WORKER_POLL_INTERVAL_MS:-2000}"
write_kv PROCESSING_STALE_MS "${PROCESSING_STALE_MS:-1800000}"
write_kv WORKER_BACKOFF_ON_PREFERRED "${WORKER_BACKOFF_ON_PREFERRED:-true}"

echo "[ci] wrote docker env file: ${env_file} (values redacted)"
