// Split docs navigation into 4 top-level sidebars for navbar switching. docs/en/developer/plans/z91bv632ewan7oocdkb4/task_plan.md z91bv632ewan7oocdkb4
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  userDocs: [
    'user-docs/index',
    'user-docs/quickstart',
    // Add TaskGroup preview guide to user docs navigation. docs/en/developer/plans/3ldcl6h5d61xj2hsu6as/task_plan.md 3ldcl6h5d61xj2hsu6as
    'user-docs/preview',
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'user-docs/config/repositories',
        // Add dependency config documentation entry. docs/en/developer/plans/depmanimpl20260124/task_plan.md depmanimpl20260124
        'user-docs/config/hookcode-yml',
        'user-docs/config/robots',
        'user-docs/config/triggers',
      ],
    },
    // Expose custom Docker image guidance for additional runtimes. docs/en/developer/plans/depmanimpl20260124/task_plan.md depmanimpl20260124
    'user-docs/custom-dockerfile',
    'user-docs/environment',
    'user-docs/features',
    'user-docs/troubleshooting',
  ],
  apiReference: [
    'api-reference/index',
    'api-reference/auth-users',
    'api-reference/repositories',
    'api-reference/tasks-and-groups',
    'api-reference/webhooks-events-tools',
  ],
  developerDocs: [
    'developer/index',
    {
      type: 'category',
      label: 'Plans',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'developer/plans'}],
    },
  ],
  changeLog: ['change-log/index', 'change-log/0.0.0'],
};

export default sidebars;
