// Split docs navigation into 4 top-level sidebars for navbar switching. docs/en/developer/plans/z91bv632ewan7oocdkb4/task_plan.md z91bv632ewan7oocdkb4
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  userDocs: [
    'user-docs/index',
    'user-docs/quickstart',
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'user-docs/config/repositories',
        'user-docs/config/robots',
        'user-docs/config/triggers',
      ],
    },
    'user-docs/environment',
    'user-docs/features',
    'user-docs/troubleshooting',
  ],
  apiReference: [
    'api-reference/index',
    'api-reference/auth-users',
    'api-reference/repositories',
    'api-reference/tasks-and-groups',
    'api-reference/webhooks-events-tools',
  ],
  developerDocs: [
    'developer/index',
    {
      type: 'category',
      label: 'Plans',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'developer/plans'}],
    },
  ],
  changeLog: ['change-log/index', 'change-log/0.0.0'],
};

export default sidebars;
